### PR TITLE
Add support for using PostgreSQL database for storing mediator agent inbox records

### PR DESCRIPTION
**Pull request by acuderman**
#### Short description of what this resolves:

Add support for storing inbox records using the Postgres storage plugin on the Mediator agent.

#### Changes proposed in this pull request:

- Propagate storage credentials and storage configuration used for the storage plugins.
- Bump NuGet package version.
- Unit tests for the case when credentials and configuration options are set.
- Expand WalletStorageConfiguration so that values don't get removed inside recordService.AddAsync(agentContext.Wallet, inboxRecord) call.

**Fixes**: #

### CODE REVIEW

**Comment by acuderman** [comment]
@tmarkovski This PR is ready for review. We had issues connecting to the Postgres database and figured out that credentials were not propagated. Thanks and feel free to suggest any improvements.

**Comment by acuderman** [comment]
Putting it to draft state. I will add all options defined in Postgres plugin to the wallet storage configuration model

**Comment by acuderman** [comment]
Putting It into a draft state since It breaks SQLLite implementation

**Comment by acuderman** [comment]
> Putting It into a draft state since It breaks SQLLite implementation

It didn't actually break an SQLlite. I just had some problems with my environment. Resolving draft state and awaiting review.

**Review by tmarkovski — APPROVED** [review]

**Comment by acuderman** [comment]
@tmarkovski thanks for the review. Can you please also update the Nuget package? The version number was already updated in this MR.

**Pull request merged**
