### PR TITLE
Use the new Hyperledger.Aries package

### PR DESCRIPTION
**Pull request by jeffallen**

### CODE REVIEW

**Comment by tmarkovski** [comment]
Thanks for the PR @jeffallen . Unfortunately, we can't have large binary files in the repo, per Hyperledger's policies. This is why we removed them when we migrated the repo here. 
The only way we can get around this is to add a script that will pull them over from sovrin repo and add some instructions on how to run the script before building the project.

@ryjones Is my understanding on the binary files correct or are we OK to add them?

**Comment by ryjones** [comment]
> @ryjones Is my understanding on the binary files correct or are we OK to add them?

you are correct. We have a bintray subscription if you want to publish there - we are also paying for artifactory which is more for CI. Furthermore, you could publish to GitHub packages.

**Comment by jeffallen** [comment]
OK, I spent a whole lotta time trying to have a "download.android.libs.sh" thing there, but I also found that the libindy.so published from repo.sovrin.net is not usable in Android right now due to TEXTREL (text relocations) which are refused by Android.

I will fix this PR to not have any libs in it at all for the moment, and then users will just have to figure out how to get them until I have something more automatic working.

**Comment by ryjones** [comment]
@jeffallen I think a publication step to Artifactory or BinTray should make all of this easier. I was working on it over here: https://github.com/hyperledger/aries-framework-dotnet/blob/master/azure-pipelines.yml but I'll take another stab after the holidays

**Comment by tmarkovski** [comment]
Thanks @jeffallen - The TEXTREL issue is tracked here https://jira.hyperledger.org/browse/IS-1434
Once that's resolved, we'll push a script to download the libraries and prepare environment for build.

**Pull request merged**
